---
title: "ESG Pilot Project"
output:
  html_document: default
  word_document: default
  pdf_document: default
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<br />
<br />

# IoT 데이터 기반 에너지 절약 머신러닝 적용 파일럿 프로젝트

<br />
<br />

## 프로젝트 진행 개략적 일정  - 빅데이터 분석 방법론 참조

<br />

- 노션과 깃허브를 통한 프로젝트 진행 상황 업데이트 
- 분석 기획 -> 데이터 준비 -> 데이터 분석 -> 시스템 구현 -> 평가 및 전개  
- 애자일 개발 적용  
-  1차 (1월-4월) -> 2차 (5월 2주차) -> 3차 (5월 4주차) -> 4차 (6월 2주차) -> 최종 (6월 30일)

<br />

### 분석기획

<br />

#### 프로젝트 범위

<br />

- 사내 또는 마이워크스페이스의 IoT 디바이스들에서 수집된 데이터를 기반으로 에너지 절약 솔루션에 적용될 머신러닝 모델 개발
-  최종 결과물
    + 대시보드 형태의 데이터 시각화 및 머시러닝 실행 웹 앱(실시간 서비스 전단계) 
        + Dash, Shiny 또는 Streamlit 으로 개발
    + 프로젝트 결과 보고서

<br />

#### 프로젝트 정의

- 아카라 디바이스 (3rd party 디바이스 포함) 머신러닝 솔루션 개발 가능성을 타진하기 위한 선행 파이럿 프로젝트
- 마이워크스페이스의 스페이스케어 솔루션 적용 준비 (2023년 7월 이후)

<br />

#### 프로젝트 수행 로드맵

<br />

- 데이터 분석 및 머신러닝 적용 계획 (1월) 
    + 결과물:  *파이럿 프로젝트 세부 일정 및 계획서*

<br />

- 데이터 준비 (1월 - 2월)
    +  사내 데이터 수집: 아카라 디바이스 (조명스위치, 스마트 플러그 등)
    + 결과물: DB 저장 데이터

<br />

- 데이터 분석 (3월)
    + EDA 
    + 시각화 자료
    + 결과물: 
        + 대시보드 또는 notebook
        + 2-3개 머신러닝 모델

<br />

- 시스템 구현 (4월 2주차)
    + 머신러닝 모델 구현 대시보드 설계
    + 결과물: 
        + 머신러닝 대시보드: Streamlit 웹앱, Jupyter notebook, 또는 R Markdown

<br />

- 평가 및 전개 (4월 4주차)
    +   1차 데모
    +   프로젝트 1차 평가 및 모델 발전 계획 수립 
    +   결과물: 
         + 모델 발전 계획서

<br />

- 2차 (5월 2주차)
    + 위 개발과정 반복 (주단위 접검)
    + 결과물: 
        + 머신러닝 대시보드: Streamlit 웹앱, Jupyter notebook, 또는 R Markdown

<br />

- 3차 (5월 4주차)
    + 위 개발과정 반복 (주단위 접검)
    + 결과물: 
        + 머신러닝 대시보드: Streamlit 웹앱, Jupyter notebook, 또는 R Markdown

<br />

- 4차 (6월 2주차)
    + 위 개발과정 반복 (주단위 접검)
    + 결과물: 
        + 머신러닝 대시보드: Streamlit 웹앱, Jupyter notebook, 또는 R Markdown

<br />

- 파이럿 프로젝트 완료 (6월 30일)
    + 결과물:
        + 머신러닝 대시보드: Dash, Shiny 또는 Streamlit
        + 프로젝트 결과 보고서

<br />

### 데이터 준비

<br />

#### 데이터 수집 범위

<br />

- 사내 아카라 디바이스 데이터
    + 조명스위치 및 스마트 플러그의 경우 ***사용 전력량*** 수집
- 양주시 프로젝트 데이터
- 마이워크스페이스

<br />

#### 데이터 스토어 설계

- 물리적 데이터 스토어
    + MySQL을 이용한 정형 데이터 저장
    + ***비정형 데이터 수집 여부*** 결정 - NoSQL 사용 여부

<br />


#### 데이터 정합성 점검

<br />

- 수집된 데이터 품질 점검
    + 수집된 데이터 포맷 필요시 변경

### 데이터 분석

<br />

#### 데이터 전처리 및 피처엔지니어링

<br />

- 수집된 소스(사내/양주시/마이워크스페이스)가 다른 데이터 결합
- 결측치/이상치 처리/정규화
- 필요 피처 생성: 예> 온도,습도 -> 불쾌지수 -> 냉난방기 제어 관련


#### 데이터 분석

<br />

- 아카라센서들과 아카라및 기타 제조사의 조명스위치,콘센트,스마트플러그 사용 패턴 (사용 전력량 포함)과의 상관 관계 파악
- 냉난방기 제어와 관련한 사용 패턴 및 온습도 패턴등 파악

<br />

#### 모델링

<br />

- 머신러닝(배깅/부스팅/시계열) or 딥러닝(LSTM,GRU, Autoencoder ...)
- 2-3 이상 모델 

<br />

### 시스템 구현

<br />

#### 머신러닝 대시보드 설계

<br />

- 데이터 분석 및 시각화 기능 포함
    + 피처별 통계 정보
    + 피처간 상관 관계
    + 시각화 옵션 부여
- 머신러닝 기반 예측 및 제어
    + DB에 직접 액세스 (or API)해서 최신 데이터 기반 전력량 예측
    + 조명 및 냉난방기 제어

<br />

#### 머신러닝 대시보드 구현

<br />

- Dash, Streamlit 또는 Shiny 중 선택 구현
- 파이럿프로젝트 1단계에서는 구현이 용이한 Streamlit 사용
- 2단계 이후 Dash 또는 Shiny선택

<br />

### 평가 및 전개

<br />

#### 프로젝트 평가 및 전개

<br />

- 프로젝트 결과 데모 (머신러닝기반 대시보드)
- 피드백 기반 마이워크스페이스 적용 범위 확정

<br />

#### 프로젝트 최종 결과물

<br />

- 머신러닝기반 대시보드 (Dash or Shiny)
- 프로젝트 결과 보고서

